version: 2.1
aliases:
  - &restore-cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "gradle.properties" }}
        - v1-dependencies-
  - &save-cache
    save_cache:
      paths:
        - ~/.gradle/wrapper
        - ~/.gradle/caches
      key: v1-dependencies-{{ checksum "gradle.properties" }}


  - &defaults
    docker:
      - image: cimg/openjdk:11.0

commands:
  run-with-dependencies:
    parameters:
      steps:
        description: "Steps that will be executed after loading dependencies"
        type: steps
    steps:
      - checkout
      - *restore-cache
      - steps: << parameters.steps >>

jobs:
  create-cache:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - run: ./gradlew dependencies
      - *save-cache
  lint:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew ktlintCheck --info
  deploy:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew publishPlugin -Pversion=$(echo $CIRCLE_BRANCH | cut -f2 -d-)
workflows:
  version: 2
  build-verify-deploy:
    jobs:
      - create-cache
      - lint:
          requires:
            - create-cache
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - /^release-.*$/